version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
    depends_on:
      - db
      - redis
    ports:
      - '${API_PORT}:${API_PORT}'
    env_file:
      - .env
  db:
    image: postgres:16.1-alpine3.19
    restart: always
    ports:
      - '${DB_PORT}:${DB_PORT}'
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
  redis:
    image: redis:7.2.3-alpine
    restart: always
    ports:
      - '${REDIS_PORT}:${REDIS_PORT}'

